id: A7262A64A
title: Prayer to Jamyang Khyentse Wangpo and Jamyang Khyentse Chökyi Lodrö
type: translation
pechas:
- I4B4A3E3B
- I2BD79DD1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:36.163142
  last_modified_at: 2023-01-04 12:35:36.163148
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I4B4A3E3B/4EA4: 84BB
  I2BD79DD1/49AD: 84BB
